site_name: Cours de première année de Master SSE
docs_dir: Docs/

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: true
  language: "fr"
  extra:
    social:
      - type: "github"
        link: "https://github.com/Lizeem"
      - type: "linkedin"
        link: "https://www.linkedin.com/in/emma-lizeski-837899149/"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true