site_name: Cours de première année de Master SSE
docs_dir: Docs/

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: true
  language: "fr"
  extra:
    social:
      - type: "github"
        link: "https://github.com/Lizeem"
      - type: "linkedin"
        link: "https://www.linkedin.com/in/emma-lizeski-837899149/"
